gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin
    panda_joint1:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    panda_joint2:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    panda_joint3:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    panda_joint4:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    panda_joint5:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    panda_joint6:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
    panda_joint7:
      p: 50.0
      i: 0.2
      d: 0.08
      i_clamp: 0.2
      antiwindup: true
      publish_state: true
